### PR TITLE
ZF3 Support, BC break

### PR DESCRIPTION
**Pull request by Saeven**
Also a little bit of PSR2 loving ;)

### CODE REVIEW

**Comment by stefanotorresi** [comment]
@Saeven could you please remove CS related changes? They're entirely subjective and I don't see reason to include them in this PR.

**Comment by exptom** [comment]
Any chance of getting ZF3 compat merged?

**Comment by stefanotorresi** [comment]
@exptom I guess I'll cherry pick the relevant commits.

**Comment by exptom** [comment]
@stefanotorresi I have opened PR #3 with just the ZF3 fixes and not all the extra CS changes if you are able to merge and tag please :-)

**Comment by stefanotorresi** [comment]
superseded by #3

**Pull request closed without merging**
